# See documentation for this workflow here:
# https://github.com/lsegal/github-release-from-changelog-action

name: "Create Release"

on:
  push:
    tags:
      - "v*"
jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub Release
        uses: yashanand1910/standard-release-notes@latest
        with:
          changelog_path: ./CHANGELOG.md
          version: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
